# Site settings
title: Extra Dope
email: makertolentino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Audio documentaries of the life and times of hip-hop artist, Son of Ran
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://extradope.github.io" # the base hostname & protocol for your site
twitter_username: techtolentino
github_username:  techtolentino

# Post settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /tapes/:year/:month/:day/:title



# Build settings
markdown: kramdown


